### ISSUE TITLE
文档无法生成html

### ISSUE THREAD

**Issue by zhangyf02** [zhangyanling77/zyl-docs#9]
wait Rendering static HTML...
error Error rendering /: false
undefined
error Error rendering /components/button.html: false
undefined
error Error rendering /components/carousel.html: false
undefined
error Error rendering /components/container.html: false
undefined
error Error rendering /components/date-picker.html: false
undefined
error Error rendering /components/icon.html: false
undefined
error Error rendering /components/infinite-scroll.html: false
undefined
error Error rendering /components/input.html: false
undefined
error Error rendering /components/layout.html: false
undefined
error Error rendering /components/pagination.html: false
undefined
error Error rendering /components/popover.html: false
undefined
error Error rendering /components/progress.html: false
undefined
error Error rendering /components/table.html: false
undefined
error Error rendering /components/upload.html: false
undefined
error Error rendering /404.html: false
undefined
ReferenceError: window is not defined
    at Object.ceb (zyl-ui/src/styles/icon.js:1:35791)
    at n (zyl-ui/webpack/bootstrap:19:21)
    at Module.fb15 (server-bundle.js:61124:16)
    at n (zyl-ui/webpack/bootstrap:19:21)
    at 00ee (zyl-ui/webpack/bootstrap:83:9)
    at server-bundle.js:55311:4
    at server-bundle.js:55259:130
    at Object.<anonymous> (zyl-ui/webpack/universalModuleDefinition:10:20)
    at Object.<anonymous> (server-bundle.js:63035:30)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (server-bundle.js:107748:22)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (server-bundle.js:63486:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at server-bundle.js:118:18
    at Object.<anonymous> (server-bundle.js:121:10)

**Comment by zhangyanling77** [comment]
zyl-ui这个项目下载了吗，npm link 到全局，然后在zyl-docs下 npm link zyl-ui 再试试呢

**Comment by zhangyanling77** [comment]
这个问题主要是vuepress ssr的时候node环境读不到window对象引起的
解决如下：
https://github.com/zhangyanling77/zyl-ui/commit/d06e52d3bfe32573473be438cc35e906ee201ac5

**Comment by zhangyf02** [comment]
谢谢作者,给你发完消息后,我也自行解决掉了问题
百忙之中 还能进行解决 万分感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhangyanling77/zyl-docs"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月15日(星期五) 下午4:28
收件人:&nbsp;"zhangyanling77/zyl-docs"<zyl-docs@noreply.github.com&gt;;
抄送:&nbsp;"旺：张余烽"<306206452@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [zhangyanling77/zyl-docs] 文档无法生成html (#9)





 
这个问题主要是vuepress ssr的时候node环境读不到window对象引起的
 解决如下：
 zhangyanling77/zyl-ui@d06e52d
